Dict: More words2
codespell-project/codespell pull request #1697
Opened 2020-10-02 18:24 UTC by sebweb3r

2020-10-02 18:29 UTC, sebweb3r commented
Piecewise isn't in aspell or cambridge dictionary, however it is used in mathematics: https://en.wikipedia.org/wiki/Piecewise

2020-10-05 15:00 UTC, peternewman commented
> Piecewise isn't in aspell or cambridge dictionary, however it is used in mathematics: https://en.wikipedia.org/wiki/Piecewise

Hmm, yeah we don't currently have a dictionary for invalid to valid but unknown.

2020-10-05 15:12 UTC, peternewman requested changes
A few comments

2020-10-07 08:14 UTC, sebweb3r commented on codespell_lib/data/dictionary.txt
> +piecwise->piecewise
I added the two word version.

2020-10-07 08:19 UTC, sebweb3r commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
I deleted it.

2020-10-13 21:42 UTC, peternewman commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
It's okay for now, I was just noting for when we get round to auto-reversing the dictionary.

2020-10-17 10:09 UTC, sebweb3r commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
shall i reintroduce it?
Some further suggestions/problems?

2020-10-22 20:44 UTC, sebweb3r commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
@peternewman push

2020-10-23 22:16 UTC, peternewman commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
Yeah I think so please, it just needs considering in #1468

2020-10-23 22:23 UTC, sebweb3r commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +grey->gray
Done in 9698d5b

2020-10-23 22:37 UTC, peternewman requested changes
A comment

2020-10-23 22:37 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +farction->faction, fraction,
I'd probably favour this:
```suggestion
farction->fraction, faction,
```

Grep.app seems to agree.

Can you also add this (but in rare as it's also a medical term):
`infarction->infraction`

2020-10-24 13:17 UTC, peternewman approved these changes

2020-10-24 13:18 UTC, merged