Add excluse->exclusive, excuse,
codespell-project/codespell pull request #1703
Opened 2020-10-22 03:30 UTC by luzpaz

2020-10-22 09:39 UTC, sebweb3r commented on codespell_lib/data/dictionary.txt
> +excluse->exclusive, excuse,
```suggestion
excluse->exclude, exclusive, excuse,
```

2020-10-22 16:49 UTC, peternewman requested changes
One comment

2020-10-22 16:49 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +excluse->exclude, exclusive, excuse,
In terms of likelyhood:

```suggestion
excluse->exclude, excuse, exclusive,
```

2020-10-23 22:02 UTC, peternewman approved these changes

2020-10-23 22:02 UTC, merged