Add several spelling corrections
codespell-project/codespell pull request #1704
Opened 2020-10-22 03:32 UTC by luzpaz

2020-10-22 09:43 UTC, sebweb3r commented on codespell_lib/data/dictionary.txt
> +desnse->dense
```suggestion
desne->dense
desnse->dense
```

2020-10-22 16:52 UTC, peternewman requested changes
A few more suggestions

2020-10-22 16:52 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +dicationary->dictionary
```suggestion
dicationaries->dictionaries
dicationary->dictionary
```

2020-10-22 16:52 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +striaght->straight
```suggestion
striaght->straight
striaghten->straighten
striaghtens->straightens
striaghts->straights
```

2020-10-23 22:14 UTC, peternewman approved these changes

2020-10-23 22:14 UTC, merged