Dict: Add complain*
codespell-project/codespell pull request #1713
Opened 2020-10-27 19:29 UTC by sebweb3r

No my flake is comlaining

_Originally posted by @sebweb3r in https://github.com/codespell-project/codespell/pull/1690#discussion_r512931323_

2020-10-28 04:43 UTC, peternewman requested changes
A few suggestions

2020-10-28 04:43 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +comlained->complained
Add
```suggestion
comlainer->complainer
```

2020-10-28 04:43 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +comlains->complains
```suggestion
comlains->complains
comlaint->complaint
comlaints->complaints
```

2020-10-28 09:39 UTC, sebweb3r commented
done.

2020-10-29 00:32 UTC, peternewman approved these changes

2020-10-29 00:32 UTC, merged