Add misspell: countermeasure, kernel, pthread, thermistor
codespell-project/codespell pull request #1830
Opened 2020-12-21 02:46 UTC by vikivivi

* New entry words: counterfeits, countermeasure, countermeasures, counterparts, coverages, thermistor, thermistors
* Typical code search:
  * https://github.com/search?q=countermeausures&type=code
  * https://github.com/search?q=coutermeasueres&type=code
  * https://github.com/search?q=coutermeasures&type=code
  * https://github.com/search?q=kernerl&type=code
  * https://github.com/search?q=phtread&type=code
  * https://github.com/search?q=thermisor&type=code

2021-02-19 17:38 UTC, peternewman requested changes
A few improvements please

2021-02-19 17:38 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +coverges->coverages
Suggest converges too

2021-02-19 17:38 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  coverge->coverage
Suggest converge too

2021-02-24 01:49 UTC, vikivivi commented
@peternewman As per your change request, both `converge` and `converges` are added to suggestion.

2021-02-24 22:48 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +coverges->coverages
Done

2021-02-24 22:49 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  coverge->coverage
Done

2021-02-24 22:52 UTC, peternewman requested changes
Sorry @vikivivi , one more comment

2021-02-24 22:52 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +couters->counters
Suggest routers and scouters, the latter is possibly a bit niche but hopefully okay
```suggestion
couters->counters, routers, scouters,
```

2021-02-27 16:24 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +couters->counters
Thanks

2021-02-27 16:25 UTC, peternewman approved these changes
Thanks @vikivivi

2021-02-27 16:25 UTC, merged