Add misspellings for certificate, garbage, integrate, policy, subsequent and view
codespell-project/codespell pull request #1839
Opened 2020-12-28 17:57 UTC by fishilico

The misspellings occur frequently:

* https://grep.app/search?q=certficiate
* https://grep.app/search?q=garbadge
* https://grep.app/search?q=integarte
* https://grep.app/search?q=poicy
* https://grep.app/search?q=subsequnt
* https://grep.app/search?q=veiw

2021-01-09 16:55 UTC, peternewman requested changes
A few more suggestions

2021-01-09 16:55 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +certficiation->certification
Also:
`certfy->certify`

2021-01-09 16:55 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +integarted->integrated
Also the integrates variant,

2021-01-09 16:55 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +preveiws->previews
Also previewed, previewer

2021-01-09 16:55 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +reveiwing->reviewing
Also reviews, reviewer, reviewers

2021-01-09 16:55 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +veiwers->viewers
Also viewed, viewing, viewings

2021-01-14 20:02 UTC, fishilico commented
Thanks for your comments! I added your variations and some more.

2021-01-14 21:34 UTC, peternewman approved these changes

2021-01-14 21:34 UTC, merged