Dict: Add *sourc*
codespell-project/codespell pull request #1842
Opened 2020-12-30 03:32 UTC by sebweb3r

inspired by #1840

2021-01-09 17:26 UTC, peternewman requested changes
A few more comments

2021-01-09 17:26 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +resourcse->resources, resource,
Add resourcd typo too.

2021-01-09 17:26 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +sourcse->sources, source,
Add sourcd typo

2021-01-14 21:57 UTC, sebweb3r commented
push @peternewman

2021-01-14 22:34 UTC, peternewman approved these changes
LGTM thanks @sebweb3r

2021-01-14 22:34 UTC, merged