Add typo variations for 'serialize'
codespell-project/codespell pull request #1856
Opened 2021-01-16 12:17 UTC by luzpaz

2021-01-18 15:57 UTC, peternewman requested changes
Just the UK side to cover

2021-01-18 15:57 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +deserialzing->deserializing
Can you also add the ise versions of all of this for the UK.

2021-01-18 15:57 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +serialzing->serializing
Can you also add the ise versions of all of this for the UK.

2021-01-18 15:58 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  sergent->sergeant
```suggestion
sergent->sergeant
serailize->serialize
```

2021-01-24 00:06 UTC, peternewman commented
I don't see any changes @luzpaz !

2021-01-24 12:54 UTC, luzpaz commented
Apologies, I rebased this PR without looking at your feedback, @peternewman. Should be complete now. Please review

2021-01-24 13:09 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +deserialzing->deserializing
Done.

2021-01-24 13:09 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +serialzing->serializing
Done

2021-01-24 13:11 UTC, peternewman requested changes
Just one outstanding comment

2021-01-24 13:11 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  serailzed->serialized
Would you mind adding the UK versions of these ones too please?

2021-04-11 00:35 UTC, peternewman requested changes
Just clarifying the existing requests

2021-04-11 00:35 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  serailzed->serialized
@luzpaz serailise and friends are still missing.

2021-04-11 00:35 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +serailize->serialize
Like this, but also -ed etc.

```suggestion
serailise->serialise
serailization->serialization
serailize->serialize
```

2021-04-12 01:16 UTC, peternewman requested changes
Just one outstanding group of UK equivalents please @luzpaz

2021-04-12 01:16 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  serailzed->serialized
Can you add the the UK versions of these ones too please?

2021-06-12 14:50 UTC, bl-ue approved these changes
LGTM — @peternewman PTAL

2021-06-13 13:44 UTC, merged