Add variations typos of 'trick'
codespell-project/codespell pull request #1866
Opened 2021-01-29 12:48 UTC by luzpaz

2021-02-19 17:56 UTC, peternewman requested changes

2021-02-19 17:56 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +trik->trick
Suggest trike too

2021-02-19 17:56 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +triks->tricks
Also trikes

2021-02-20 11:24 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +triks->tricks
8c45e8b

2021-02-20 11:24 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +trik->trick
8c45e8b

2021-02-20 11:25 UTC, luzpaz commented
Added requested revisions + added `trikery->trickery`

Please merge

2021-02-20 23:18 UTC, peternewman approved these changes

2021-02-20 23:18 UTC, merged