Add variation typos for 'appreciate'
codespell-project/codespell pull request #1873
Opened 2021-02-05 10:51 UTC by luzpaz

2021-02-06 09:22 UTC, ssbarnea approved these changes

2021-02-19 13:09 UTC, peternewman requested changes
Add appreciative variants, also unappreciated etc

2021-06-11 12:55 UTC, bl-ue commented
ping @luzpaz — can I do this for you?

2021-06-11 16:51 UTC, bl-ue approved these changes
LGTM.  @peternewman PTAL :)

2021-06-13 15:03 UTC, merged