Added several spelling corrections
codespell-project/codespell pull request #1893
Opened 2021-03-19 11:17 UTC by luzpaz

2021-06-07 12:48 UTC, luzpaz commented
@peternewman ready for review

2021-06-07 12:58 UTC, bl-ue approved these changes

2021-06-11 12:38 UTC, bl-ue requested changes

2021-06-11 12:38 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +briter->brighter
Add `briten` and variants?
```suggestion
brite->bright
briten->brighten
britened->brightened
britener->brightener
briteners->brighteners
britenes->brightenes
britening->brightening
briter->brighter
```

2021-06-11 12:38 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +rrrors->errors
Add `rrrored` and `rrroring`?
```suggestion
rrror->error
rrrored->errored
rrroring->erroring
rrrors->errors
```

2021-06-11 12:38 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +suppurted->supported
Add `suppurter` and `suppurters`?
```suggestion
suppurt->support
suppurted->supported
suppurter->supporter
suppurters->supporters
```

2021-06-11 12:38 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +trilinar->trilinear
Suggest `trillionaire` & add `trilinars`?
```suggestion
trilinar->trilinear, trillionaire,
trilinar->trillionaire
```

2021-06-12 14:30 UTC, bl-ue commented
ping @luzpaz did this get lost?

2021-06-15 13:11 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +chanaged->changed
```suggestion
chanaged->changed
chanager->changer
```

2021-06-15 13:11 UTC, bl-ue approved these changes

2021-06-15 13:26 UTC, merged