Add variants of octothorpe (the '#' character)
codespell-project/codespell pull request #1906
Opened 2021-04-02 13:50 UTC by bl-ue

https://en.wiktionary.org/wiki/octothorpe

2021-04-05 14:15 UTC, peternewman requested changes
Are these actual or generated?

2021-04-05 14:15 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +octothorpe->octothorpe
This one just corrects to itself!

2021-04-05 14:16 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +octotthorpes->octothorpe
This should probably be removed!

2021-04-05 14:26 UTC, bl-ue commented
>Are these actual or generated?

Both, in a way. 🙂  I manually typed some likely typos as this is rather long word, and then I used VS Code multi-cursor to mess them up a bit more.

>This should probably be removed!

Yeah, they're rather silly I admit.  There were actually more before I opened PR but I trimmed some down... 😄

2021-04-05 14:26 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +octothorpe->octothorpe
```suggestion
```

2021-04-05 14:27 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +octotthorpes->octothorpe
```suggestion
```

2021-04-05 14:27 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +octotthorpes->octothorpe
```suggestion
```

2021-04-05 14:59 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +octothhorpes->octothorpes
We should at least have the singular

2021-04-05 15:01 UTC, peternewman commented
> > Are these actual or generated?
> 
> Both, in a way. slightly_smiling_face I manually typed some likely typos as this is rather long word, and then I used VS Code multi-cursor to mess them up a bit more.

I'm not sure we should necessarily be flooding the dictionary with random potential typos, it would be nice to see some real world examples that some of these exist as a base, even if we then add the plural etc for example.

2021-04-05 15:09 UTC, bl-ue commented
Okay, I'll keep the simple obvious ones and get rid of the less likely ones.  How about that?

2021-04-11 00:31 UTC, peternewman commented
> Okay, I'll keep the simple obvious ones and get rid of the less likely ones. How about that?

In case my :+1: wasn't explicit enough, that sounds good to me.

2021-05-17 13:20 UTC, closed without merging

2021-05-18 12:55 UTC, peternewman commented
What happened @bl-ue ? I thought you were going to just sort the simple/obvious ones?

2021-05-18 14:41 UTC, bl-ue commented
Since I opened this PR, I realized that it's better to provide known typos, rather than possible ones.  None of these I've ever actually seen, so I figured it's just a waste of time.  There's much more interesting work that can be done in terms of adding to the database :wink: