Add aperure(s)->aperture(s)
codespell-project/codespell pull request #1940
Opened 2021-06-09 18:31 UTC by luzpaz

2021-06-09 21:44 UTC, bl-ue requested changes

2021-06-09 21:44 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +aperures->apetures
```suggestion
aperure->aperture
aperures->apertures
```

2021-06-09 23:12 UTC, luzpaz commented
Thanks @bl-ue, added you revision in ac169f5  
Also added 81fe61c

2021-06-10 00:26 UTC, bl-ue approved these changes

2021-06-11 13:02 UTC, merged