Add typo variations for 'inherit'
codespell-project/codespell pull request #1992
Opened 2021-06-22 20:53 UTC by luzpaz

2021-06-22 21:06 UTC, bl-ue requested changes

2021-06-22 21:06 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +inerits->inherits
Add `ineritor` & `ineritors`?
```suggestion
inerit->inherit
ineritance->inheritance
inerited->inherited
ineriting->inheriting
inerits->inherits
ineritor->inheritor
ineritors->inheritors
```

2021-06-23 00:39 UTC, bl-ue reviewed
Ooops!

2021-06-23 00:39 UTC, bl-ue commented on codespell_lib/data/dictionary.txt
> +ineritors->inheritors
```suggestion
inerit->inherit
ineritance->inheritance
inerited->inherited
ineriting->inheriting
ineritor->inheritor
ineritors->inheritors
inerits->inherits
```

2021-06-23 01:55 UTC, bl-ue approved these changes

2021-06-23 01:55 UTC, merged

2021-06-23 01:56 UTC, bl-ue commented
@luzpaz, you were invited to join the organization. https://github.com/codespell-project

2021-06-23 02:13 UTC, luzpaz commented
Thanks @bl-ue, but i see no invitation there