Add some typos seen in the wild.
codespell-project/codespell pull request #2169
Opened 2021-11-17 12:21 UTC by jtroup

2021-12-04 11:41 UTC, peternewman requested changes
Some more variants

2021-12-04 11:41 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +proedure->procedure
More variants:
```suggestion
proedural->procedural
proedure->procedure
proedures->procedures
```

2021-12-04 11:41 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +profie->profile
Again:
```suggestion
profie->profile
profied->profiled
profier->profiler
profies->profiles
```

2021-12-04 11:41 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +usptart->upstart
```suggestion
usptart->upstart
usptarts->upstarts
```

2021-12-26 17:35 UTC, luzpaz commented
@jtroup please follow-up

2021-12-27 17:13 UTC, merged