More misspellings
codespell-project/codespell pull request #2171
Opened 2021-11-18 03:45 UTC by DimitriPapadopoulos

See [openconnect/ocserv#276](https://gitlab.com/openconnect/ocserv/-/merge_requests/276).

https://github.com/search?q=happilly&type=code
https://github.com/search?q=incomping&type=code
https://github.com/search?q=oher&type=code
https://github.com/search?q=permamently&type=code
https://github.com/search?q=singature&type=code

2021-11-18 22:50 UTC, luzpaz approved these changes

2021-12-02 13:45 UTC, peternewman requested changes
One comment

2021-12-02 13:45 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +oher->other
Suggest her too

2021-12-02 16:21 UTC, DimitriPapadopoulos commented on codespell_lib/data/dictionary.txt
> +oher->other
Done

2021-12-03 05:24 UTC, peternewman approved these changes

2021-12-03 05:24 UTC, merged