A few more mispellings
codespell-project/codespell pull request #2180
Opened 2021-11-27 17:39 UTC by DimitriPapadopoulos

See https://github.com/Blosc/c-blosc2/pull/366.

2021-12-02 13:34 UTC, peternewman requested changes
Can you add `bumber` to bumped and I guess bummer. Maybe `bumby` too

2021-12-02 15:56 UTC, DimitriPapadopoulos commented
And probably `bombed`.

2021-12-02 16:46 UTC, DimitriPapadopoulos commented
Note than `bumb` is slang:
https://www.urbandictionary.com/define.php?term=bumb

2021-12-03 05:23 UTC, peternewman requested changes
A few more sorry

2021-12-03 05:23 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +bumb->bump, bomb,
Perhaps suggest bum too, which is what I'd expect for the homeless person or the bottom.

2021-12-03 05:23 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +bumber->bumper, bomber,
```suggestion
bumber->bumper, bomber, bummer,
```

2021-12-04 11:34 UTC, peternewman approved these changes

2021-12-04 11:34 UTC, merged