code: add typdef->typedef
codespell-project/codespell pull request #2219
Opened 2021-12-31 13:07 UTC by luzpaz

Add `typdef->typedef` to code dictionary

2022-01-02 17:44 UTC, peternewman requested changes
This is a typo applicable to code, so it goes in the normal dictionary!

2022-01-02 19:02 UTC, luzpaz commented
@peternewman Yikes, that was a mistake on my part. Corrected in d203ba1bf5d

2022-01-02 23:43 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +typdef->typedef
Possibly suggest typed too as another correction.

2022-01-03 01:09 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +typdef->typedef
53b8a29

2022-01-03 12:55 UTC, peternewman approved these changes

2022-01-03 12:55 UTC, merged