More misspellings
codespell-project/codespell pull request #2235
Opened 2022-01-12 22:30 UTC by DimitriPapadopoulos

See https://github.com/jjhelmus/nmrglue/pull/165.

2022-01-13 00:48 UTC, luzpaz approved these changes

2022-01-13 11:00 UTC, luzpaz requested changes

2022-01-13 11:00 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +controlller->controller
Please add: 
```
controllled->controlled
controlllers->controllers
controllling->controlling
```

2022-01-13 11:00 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +decompositon->decomposition
Please add `decompositons->decompositions`

2022-01-13 11:00 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
>  expoential->exponential
Add `expoent->exponent`

2022-01-13 11:32 UTC, DimitriPapadopoulos commented on codespell_lib/data/dictionary.txt
> +controlller->controller
Done.

2022-01-13 11:33 UTC, DimitriPapadopoulos commented on codespell_lib/data/dictionary.txt
> +decompositon->decomposition
Done.

2022-01-13 11:33 UTC, DimitriPapadopoulos commented on codespell_lib/data/dictionary.txt
>  expoential->exponential
Done.

2022-01-15 18:54 UTC, merged

2022-01-15 18:54 UTC, luzpaz commented
Thanks!