Fix several spelling corrections
codespell-project/codespell pull request #2244
Opened 2022-01-17 16:39 UTC by luzpaz

2022-01-25 02:20 UTC, vikivivi commented
I think the checks failed because suggestion is the same as misspell. Do you mean to suggest `encryption`?
```text
encription->encription
```
1. Shall we capitalise the word '`Fibonacci`? It is a name of a person.
```text
encription->encryption
fibonaacci->Fibonacci
```
2. Shall we add these additional misspell?
```text
adapations->adaptations, adoptions,
affinties->affinities
encompasing->encompassing
initializad->initialized
seamlessley->seamlessly
seeverity->severity
stategies->strategies
varously->variously
```
* https://github.com/search?q=adapations&type=code
* https://github.com/search?q=affinties&type=code
* https://github.com/search?q=encompasing&type=code
* https://github.com/search?q=initializad&type=code
* https://github.com/search?q=seamlessley&type=code
* https://github.com/search?q=seeverity&type=code
* https://github.com/search?q=stategies&type=code
* https://github.com/search?q=varously&type=code

2022-01-26 00:56 UTC, isaak654 requested changes

2022-01-26 00:56 UTC, isaak654 commented on codespell_lib/data/dictionary.txt
> +fibonaacci->fibonacci
He was a famous mathematician, so:
```suggestion
fibonaacci->Fibonacci
```

2022-01-26 00:56 UTC, isaak654 commented on codespell_lib/data/dictionary.txt
> +encription->encription
```suggestion
encription->encryption
```

2022-01-28 08:17 UTC, vikivivi approved these changes
LGTM

2022-02-02 18:55 UTC, merged