Add more incorrect words
codespell-project/codespell pull request #2261
Opened 2022-01-29 21:30 UTC by isaak654

2022-01-30 13:51 UTC, luzpaz approved these changes

2022-02-01 17:05 UTC, peternewman requested changes
A few improvements please.

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +mdoes->modes
Suggest does too.

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +mdoe->mode
Suggest doe (female deer) too

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +logner->longer
Suggest logger too

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +creaters->creators
Suggest craters too

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +creatin->creation, creating, creatine,
Suggest cretin too

2022-02-01 17:05 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +cerated->created
Suggest serrated too

2022-02-01 17:25 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +cerated->created
Done

2022-02-01 17:26 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +logner->longer
Done

2022-02-01 17:26 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +mdoe->mode
Done

2022-02-01 17:26 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +mdoes->modes
Done.

2022-02-01 17:27 UTC, peternewman approved these changes
LGTM, thanks for the changes!

2022-02-02 02:50 UTC, luzpaz commented
LGTM

2022-02-02 02:50 UTC, luzpaz approved these changes

2022-02-02 02:51 UTC, merged