Added more common typos
codespell-project/codespell pull request #2277
Opened 2022-02-13 21:40 UTC by polluks

2022-02-14 00:14 UTC, peternewman requested changes
A few suggestions

2022-02-14 00:14 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +confimation->confirmation
```suggestion
confim->confirm
confimation->confirmation
confimations->confirmations
confimed->confirmed
confims->confirms
```

2022-02-14 00:14 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  sattelites->satellites
```suggestion
sattelit->satellite
sattelite->satellite
sattelites->satellites
sattelits->satellites
```

2022-02-16 04:53 UTC, luzpaz approved these changes

2022-02-23 19:26 UTC, FloEdelmann commented on codespell_lib/data/dictionary.txt
> +sience->science
```suggestion
sience->science,silence,
```

2022-02-23 23:48 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +sience->science,silence,
whitespace missing after first comma

2022-02-24 00:54 UTC, peternewman commented on codespell_lib/data/dictionary.txt
>  confimred->confirmed
Dictionary needs sorting:
```suggestion
confimred->confirmed
confims->confirms
```

2023-02-14 21:44 UTC, merged