More misspellings
codespell-project/codespell pull request #2280
Opened 2022-02-17 08:47 UTC by DimitriPapadopoulos

See https://github.com/cea-hpc/modules/issues/442 and https://github.com/cea-hpc/modules/pull/443.

2022-02-18 04:52 UTC, luzpaz approved these changes

2022-02-21 15:23 UTC, peternewman requested changes
One suggestion

2022-02-21 15:23 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +brakets->brackets
```suggestion
braket->bracket, brake,
brakets->brackets, brakes,
```

2022-02-21 22:35 UTC, peternewman approved these changes

2022-02-21 22:35 UTC, merged