move `outputof` to code dictionary
codespell-project/codespell pull request #2338
Opened 2022-04-26 16:23 UTC by robin-wayve

avoid false positives from https://github.com/premake/premake-4.x/wiki/os.outputof

I am also a bit surprised that the correction is `output-of` (with a dash) 🤨

2022-04-28 21:15 UTC, peternewman requested changes
Do you want to make the default correction with a space, and the secondary with the hyphen then?

2022-04-29 07:44 UTC, robin-wayve commented on codespell_lib/data/dictionary_code.txt
> +outputof->output-of
```suggestion
outputof->output of,output-of
```

2022-04-29 07:45 UTC, robin-wayve commented on codespell_lib/data/dictionary_code.txt
> +outputof->output of,output-of
```suggestion
outputof->output of, output-of
```

2022-04-29 11:40 UTC, peternewman commented on codespell_lib/data/dictionary_code.txt
> +outputof->output of, output-of
You need a trailing comma too...
```suggestion
outputof->output of, output-of,
```

2022-04-29 12:00 UTC, peternewman approved these changes
LGTM thanks.

2022-04-29 12:01 UTC, merged