Add testing and document support for Python 3.10
codespell-project/codespell pull request #2379
Opened 2022-06-25 22:36 UTC by jdufresne

Python 3.10 was released Oct 4, 2021.

https://www.python.org/downloads/release/python-3100/

2022-10-17 11:50 UTC, peternewman requested changes
Can you rebase please. I think the GitHub workflow bit has been done, setup.py is now pyproject.toml, but the programming language tags aren't in that, so may still be relevant to add.

2022-10-19 13:31 UTC, jdufresne commented on pyproject.toml
> +    "Programming Language :: Python :: 3.10",
Just a personal anecdote, I have not found maintaining this list a hardship in other projects. When adding a new version to GitHub actions, this is just one more spot. Often, volunteers see this information and add it (such as myself).

The classifiers are useful as they display on PyPI to provide quick at-a-glance info to people interested in the project as to what Python versions are supported. They could also be used by scripts to determine trends in the Python community

Is there an existing wiki article I could edit to help?

2022-10-19 16:52 UTC, peternewman commented on pyproject.toml
> +    "Programming Language :: Python :: 3.10",
> Just a personal anecdote, I have not found maintaining this list a hardship in other projects. When adding a new version to GitHub actions, this is just one more spot. Often, volunteers see this information and add it (such as myself).

Yeah, I guess it more seems a shame we have to generate/manage them at all when we've already got a computer readable minimum version field!

> The classifiers are useful as they display on PyPI to provide quick at-a-glance info to people interested in the project as to what Python versions are supported. They could also be used by scripts to determine trends in the Python community

Again it seems slightly mad the other fields can't just be used. :shrug: 

> Is there an existing wiki article I could edit to help?

Not currently, I'd say just create a new one about adding or removing support for a new version (maybe even mention to check that before cutting a new release). There's clearly already two places in this file it needs updating, plus our various CI and any readme docs...

2022-10-24 00:40 UTC, jdufresne commented on pyproject.toml
> +    "Programming Language :: Python :: 3.10",
@peternewman I added the information to the following wiki article. Pleaese let me know if you'd like to see any changes to the wording.

https://github.com/codespell-project/codespell/wiki/How-to-make-a-release

2022-11-11 19:36 UTC, jdufresne commented
Updated to include Python 3.11.

2022-11-11 20:44 UTC, DimitriPapadopoulos approved these changes

2022-11-17 13:53 UTC, peternewman commented on pyproject.toml
> +    "Programming Language :: Python :: 3.10",
Great thanks, I've added a few further nudges.

2022-11-17 13:54 UTC, peternewman approved these changes
I think I'm mostly convinced the admin overheads aren't too arduous.

Over to @larsoner or @DimitriPapadopoulos if its actually widely used/worth adding...

2022-11-17 15:11 UTC, merged

2022-11-17 15:11 UTC, larsoner commented
Thanks @jdufresne !