Add several spelling corrections
codespell-project/codespell pull request #2396
Opened 2022-07-07 11:38 UTC by kianmeng

2022-07-12 22:25 UTC, peternewman requested changes
A few minor tweaks.

2022-07-12 22:25 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +arrity->arity
You learn something new...

Maybe add:
```suggestion
arrity->arity, parity,
```

2022-07-12 22:25 UTC, peternewman commented on codespell_lib/data/dictionary.txt
> +funciotns->functions
Add the singular:
```suggestion
funciotn->function
funciotns->functions
```

2022-07-12 22:28 UTC, luzpaz commented
Apologies, I though this was one of my personal PRs. I merged the changes @peternewman requested. :cringe:

2022-07-13 14:03 UTC, peternewman approved these changes
LGTM, but it would be nice to check that @kianmeng is happy with @luzpaz unexpected changes.

2022-07-13 14:13 UTC, luzpaz commented
Yes, please weigh-in @kianmeng

2022-07-13 14:47 UTC, kianmeng commented
@peternewman @luzpaz I'm good. :smile:

2022-07-13 21:53 UTC, merged

2022-07-14 05:14 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: