Add several spelling corrections + refinements
codespell-project/codespell pull request #2441
Opened 2022-08-09 06:29 UTC by luzpaz

2022-08-09 14:31 UTC, vikivivi requested changes

2022-08-09 14:31 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +compilcates->complicates
```text
compilcatedly->complicatedly
compilcating->complicating
compilcation->complication
compilcations->complications
```
* https://github.com/search?q=compilcatedly&type=code
* https://github.com/search?q=compilcating&type=code
* https://github.com/search?q=compilcation&type=code
* https://github.com/search?q=compilcations&type=code

2022-08-09 14:31 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +consctructors->constructors
```
consctruct->construct
consctructed->constructed
consctructing->constructing
consctruction->construction
consctructions->constructions
consctructive->constructive
consctructs->constructs
```
* https://github.com/search?q=consctruct&type=code
* https://github.com/search?q=consctructed&type=code
* https://github.com/search?q=consctructing&type=code
* https://github.com/search?q=consctruction&type=code
* https://github.com/search?q=consctructions&type=code
* https://github.com/search?q=consctructive&type=code
* https://github.com/search?q=consctructs&type=code

2022-08-09 14:31 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +containes->contains, container,
Also suggest `contained` as `d` key is beside `s`
```text
containes->contains, container, contained,
```

2022-08-09 14:31 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +distinguised->distinguished
```text
distinguises->distinguishes
```
* https://github.com/search?q=distinguises&type=code

2022-08-09 14:31 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +febbruary->february
If you don't mind capitalised with `February`. Online dictionaries, browser, aspell, hunspell, ispell indicates a misspelling if it is in lower case. Thank you, if you don't mind adding these additional related 'months'.
`Februar` should be German, remove it if you think we should not add it.
```text
febbruary->February
februar->February

augest->August
novemeber->November
```
* https://github.com/search?q=febbruary&type=code
* https://github.com/search?q=februar&type=code
* https://github.com/search?q=augest&type=code
* https://github.com/search?q=novemeber&type=code

2022-08-09 19:46 UTC, luzpaz commented
Thanks, I was sloppy on this PR. Apologies. I've added your revisions and also made some of my own: [eb3c962](https://github.com/codespell-project/codespell/pull/2441/commits/eb3c962edf773c05a1ae716216365ba067e493c8)

2022-08-10 01:27 UTC, vikivivi approved these changes
LGTM

2022-08-10 02:48 UTC, merged