Add several spelling corrections and refinements
codespell-project/codespell pull request #2447
Opened 2022-08-10 01:21 UTC by luzpaz

2022-08-10 14:26 UTC, vikivivi requested changes

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +addes->adds, added, address,
Also suggest `adders`?
```text
addes->adds, added, adders, address,
```

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +alocations->allocations
Also suggest `a location`?
```text
alocation->allocation, a location,
```

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +distinations->destinations
Also suggest `distinction` ?
```text
distination->destination, distinction,
distinations->destinations, distinctions,

distinative->distinctive
```
https://github.com/search?q=distinative&type=code

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +logial->logical
```text
logially->logically
```
https://github.com/search?q=logially&type=code

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +packes->packs, packages,
Also suggest `packed` ?
```text
packes->packs, packed, packages,
```

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +poitns->points
```text
poitless->pointless
poitlessly->pointlessly
```
* https://github.com/search?q=poitless&type=code
* https://github.com/search?q=poitlessly&type=code

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +significatly->significantly
```text
insignificat->insignificant
insignificatly->insignificantly
```
* https://github.com/search?q=insignificat&type=code
* https://github.com/search?q=insignificatly&type=code

2022-08-10 14:26 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +tuseday->Tuesday
```text
teusday->Tuesday
tuesdsy->Tuesday
```
* https://github.com/search?q=teusday&type=code
* https://github.com/search?q=tuesdsy&type=code

2022-08-10 18:04 UTC, luzpaz commented
@vikivivi added requested mods and rebased. Please re-review, TIA!

2022-08-11 01:06 UTC, vikivivi approved these changes
LGTM

2022-08-11 01:28 UTC, merged