Add several spelling corrections
codespell-project/codespell pull request #2449
Opened 2022-08-14 13:40 UTC by luzpaz

@vikivivi please review, TIA!

2022-08-15 16:25 UTC, vikivivi requested changes

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +extendability->extendibility
I suggest you drop or stash this. 
`extendability` & `extendibility` are both valid as well as invalid depending on which dictionaries you consulted. Validity of both words are inconsistent across many dictionaries.

Both `extendability` & `extendibility` are valid in hunspell, aoo-mozilla-en-dict
Both `extendability` & `extendibility` are invalid in aspell, chrome browser,

`extendability` is valid in hunspell, aoo-mozilla-en-dict
`extendability` is invalid in aspell, chrome browser, ispell

`extendibility` is valid in hunspell, aoo-mozilla-en-dict, ispell
`extendibility` is invalid in aspell, chrome browser

In source code context, in my opinion, majority actually mean `extensibility`.
`extensibility` is also inconsistent in various dictionaries.

https://www.lexico.com/definition/extendability (Both valid, lexico.com has merge with dictionary.com)
https://www.merriam-webster.com/dictionary/extendability  (Both valid)
https://www.dictionary.com/misspelling?term=extendability  (Both valid)
https://wikidiff.com/extensibility/extendibility  (extendibility vs extensibility)

https://www.ldoceonline.com/spellcheck/english/?q=extendability  (Both invalid)
https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=extendability  (Both invalid)
https://dictionary.cambridge.org/spellcheck/english/?q=extendibility  (Both invalid)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +interectioned->instersectioned
Suggested word is a misspelling. At the same time `intersectioned` is also a misspell. So you might want to just suggest `intersection`. Anyway, there is only 1 hit.
```text
interectioned->intersection
```
https://github.com/search?q=interectioned&type=code (1)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +neigbhours->neighbors
I think you should suggest `en-GB` and `en-US` separately. Try not to mix both `bour` and `bor`
```
neigbhour->neighbour
neigbhours->neighbours
neigbhor->neighbor
neigbhors->neighbors
```
* https://github.com/search?q=neigbhour&type=code  (3K)
* https://github.com/search?q=neigbhours&type=code  (1K)
* https://github.com/search?q=neigbhor&type=code  (3K)
* https://github.com/search?q=neigbhors&type=code  (7K)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +ortogonal->orthogonal
```text
ortogonality->orthogonality
```
https://github.com/search?q=ortogonality&type=code  (1K)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +sevral->several
```text
sevrally->severally
```
https://github.com/search?q=sevrally&type=code  (8)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +techically->technically
You might want to suggest `tactically`?
```text
techically->technically, tactically,
```

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +transitionning->transitioning
```text
transitionnal->transitional
transitionns->transitions
```
* https://github.com/search?q=transitionnal&type=code  (2K)
* https://github.com/search?q=transitionns&type=code  (16)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +transofrms->transforms
```text
transofrmer->transformer
transofrmers->transformers
```
* https://github.com/search?q=transofrmer&type=code  (930)
* https://github.com/search?q=transofrmers&type=code  (119)

2022-08-15 16:25 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +workleds->worklets, worked,
I am not favour of this entry. This one is more like a CamelCase for workLEDs, workLeds. 
Looking at the search results seem valid coding.
Splitting `work` and `LEDs` will also break source code.
Personally, I would drop this one.

* https://github.com/search?q=workled&type=code  (234)
* https://github.com/search?q=workleds&type=code  (10)

2022-08-16 11:42 UTC, luzpaz commented
Thanks. I've added your suggestions with no objection.

2022-08-16 13:18 UTC, vikivivi approved these changes
LGTM

2022-08-16 13:29 UTC, merged