Fix various spelling corrections
codespell-project/codespell pull request #2456
Opened 2022-08-17 21:29 UTC by luzpaz

2022-08-19 14:21 UTC, vikivivi requested changes

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +deifnes->defines
```text
deifning->defining

dedfined->defined
definde->define, defined, defines,
definding->defining
```
* https://github.com/search?q=deifning&type=code  240
* https://github.com/search?q=dedfined&type=code 239
* https://github.com/search?q=definde&type=code 10922
* https://github.com/search?q=definding&type=code 1557

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +deliverying->delivering
```text
delibery->delivery
deliverys->deliveries, delivers,
```
* https://github.com/search?q=delibery&type=code 1877
* https://github.com/search?q=deliverys&type=code 15584

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +miminized->minimized
```text
miminizes->minimizes
miminizing->minimizing

miminise->minimise
miminised->minimised
miminises->minimises
miminising->minimising
```
* https://github.com/search?q=miminizes&type=code  515
* https://github.com/search?q=miminizing&type=code  366
* https://github.com/search?q=miminise&type=code  167
* https://github.com/search?q=miminised&type=code  1253
* https://github.com/search?q=miminises&type=code  6
* https://github.com/search?q=miminising&type=code  9

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +rocords->records
```text
rocorder->recorder
```
https://github.com/search?q=rocorder&type=code  259

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +specializaitons->specializations
```text
specialisaiton->specialisation
specialisaitons->specialisations
```
* https://github.com/search?q=specialisaiton&type=code  21
* https://github.com/search?q=specialisaitons&type=code  2

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +threated->threatened, treated,
Please suggest `threaded` as first choice.
```text
threated->threaded, threatened, treated,
```
* https://github.com/search?q=threated&type=code  78766

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +unsing->using, unsign,
```text
unsing->using, unsigned,
```
`unsign` is not a valid word in various dictionaries (aspell, hunspell, ispell, aoo-mozilla-en-dict, browser).
Please suggest `unsigned`. If you type `unsign integer` in Google search box before hitting ENTER key,
you will notice Google suggest you with `unsigned integer` for your search

2022-08-19 14:21 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +wastefull->wasteful
Please suggest `wastefully` as well.
```text
wastefull->wasteful, wastefully,
wastefullness->wastefulness
```
* https://github.com/search?q=wastefull&type=code  5168
* https://github.com/search?q=wastefullness&type=code  97

2022-08-29 12:46 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +reparamterization->reparameterization
Do you suggest to move to code dictionary then?

2022-08-29 13:28 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +reparamterization->reparameterization
No. Do not move to dictionary_code.txt. This is fine.
code dictionary is meant for entry where `(valid_word_from_code)->(valid_word_from_English)`.
For example: `uint->unit`, `jupyter->Jupiter`

2022-08-29 13:30 UTC, vikivivi approved these changes
LGTM

2022-08-29 15:37 UTC, merged