Add several spelling corrections
codespell-project/codespell pull request #2467
Opened 2022-08-19 05:06 UTC by ydah

This PR add some spelling corrections I detected below:
- https://github.com/rubocop/rubocop/pull/10937

2022-08-19 12:58 UTC, luzpaz requested changes

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +commnet->comment
additional entries

```
commneted->commented
commneting->commenting
commnets->comments
```

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +condidate->candidate
`condidates->candidates`

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +consntant->constant
`consntants->constants`

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +offsense->offense
`offsenses->offenses`

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary_en-GB_to_en-US.txt
> +offences->offenses
Please remove, `offence` is a valid GB spelling

2022-08-19 12:58 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +offfense->offense
`offfenses->offenses`

2022-08-19 23:34 UTC, ydah commented
I updated this PR. Thank you so much.

2022-08-20 01:34 UTC, luzpaz commented
@vikivivi care to weigh-in ?

2022-08-20 09:30 UTC, vikivivi requested changes

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +commnet->comment
```text
commnetaries->commentaries
commnetator->commentator
commnetators->commentators
```
* https://github.com/search?q=commnetaries&type=code  26
* https://github.com/search?q=commnetator&type=code  24
* https://github.com/search?q=commnetators&type=code  30

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +consntant->constant
```text
consntantly->constantly
```
https://github.com/search?q=consntantly&type=code  36

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +directove->directive
```text
directoves->directives
```
https://github.com/search?q=directoves&type=code  595

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +interporation->interpolation
```text
interporations->interpolations
```
https://github.com/search?q=interporations&type=code  32

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +lodable->loadable
```text
loded->loaded
loder->loader
loders->loaders
```
* https://github.com/search?q=loded&type=code  45512
* https://github.com/search?q=loder&type=code  107258
* https://github.com/search?q=loders&type=code  2916

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +offens->offense
Please suggest `offend, offends, offers,` as well
```text
offens->offend, offense, offends, offers,
```
* https://github.com/search?q=offens&type=code  43919

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +offfense->offense
Add `en-GB` as well
```text
offfence->offence
offfences->offences
```
* https://github.com/search?q=offfence&type=code  68
* https://github.com/search?q=offfences&type=code  33

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +offsense->offense
Ignore 0 hit plural version `offsences->offences`
```text
offsence->offence
```
* https://github.com/search?q=offsence&type=code  16
* https://github.com/search?q=offsences&type=code  0

2022-08-20 09:30 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +platfoms->platforms
```text
platfomr->platform
platfomrs->platforms
```
* https://github.com/search?q=platfomr&type=code  9470
* https://github.com/search?q=platfomrs&type=code  760

2022-08-20 12:27 UTC, ydah commented
Thank you so much! I updated this PR.

2022-08-20 13:11 UTC, vikivivi approved these changes
LGTM

2022-08-20 23:07 UTC, merged

2022-08-20 23:07 UTC, luzpaz commented
Thank you to all involved!