Add entries to the inclusive language dictionary
codespell-project/codespell pull request #2469
Opened 2022-08-19 18:08 UTC by sed-i

This PR adds entries to the `usage` inclusive language dictionary.

References:
- https://github.com/IBM/IBMInclusiveITLanguage
- https://inclusivenaming.org/word-lists/

cc: @madhens @lex-joy

2022-11-21 23:25 UTC, skangas requested changes
I only commented one, but all these alternatives are missing a comma at the end. You need to add that, or they will be disabled.

2022-11-21 23:25 UTC, skangas commented on codespell_lib/data/dictionary_usage.txt
> +cripples->slows down, hinders, obstructs
Should have a comma at the end

2022-11-29 20:53 UTC, sed-i commented
CI seems to be frozen.
Would you be able to help move this along? @peternewman @skangas

2023-02-14 23:29 UTC, DimitriPapadopoulos approved these changes

2023-02-14 23:33 UTC, merged