Add spelling correction for place
codespell-project/codespell pull request #2500
Opened 2022-09-15 18:12 UTC by adrien-berchet

2022-09-16 06:03 UTC, vikivivi requested changes

2022-09-16 06:03 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +plcae->place
```suggestion
plcae->place
plcaebo->placebo
plcaed->placed
plcaeholder->placeholder
plcaeholders->placeholders
plcaement->placement
plcaements->placements
```
* https://github.com/search?q=plcae&type=code  3852 
* https://github.com/search?q=plcaebo&type=code  7
* https://github.com/search?q=plcaed&type=code  658
* https://github.com/search?q=plcaeholder&type=code  3224
* https://github.com/search?q=plcaeholders&type=code  80
* https://github.com/search?q=plcaement&type=code  202
* https://github.com/search?q=plcaements&type=code  4
* https://github.com/search?q=plcaes&type=code  285

2022-09-16 07:15 UTC, adrien-berchet commented on codespell_lib/data/dictionary.txt
> +plcae->place
Good point, thanks!

2022-09-16 08:02 UTC, vikivivi approved these changes
LGTM

2022-09-26 00:46 UTC, merged

2022-09-26 00:47 UTC, luzpaz commented
Thanks!