interepolation->interpolation
codespell-project/codespell pull request #2512
Opened 2022-10-04 05:27 UTC by tkoyama010

See https://github.com/pyvista/pyvista/pull/3403

2022-10-05 03:22 UTC, vikivivi requested changes

2022-10-05 03:22 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +interepolation->interpolation
```suggestion
interepolate->interpolate
interepolated->interpolated
interepolates->interpolates
interepolating->interpolating
interepolation->interpolation
```

2022-10-05 03:22 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +interepolation->interpolation
I did not suggest `interpolations` due to 0 hit.

* https://github.com/search?q=interepolate&type=code  11
* https://github.com/search?q=interepolated&type=code  21
* https://github.com/search?q=interepolates&type=code  5
* https://github.com/search?q=interepolating&type=code  3
* https://github.com/search?q=interepolation&type=code  178
* https://github.com/search?q=interepolations&type=code  0

2022-10-19 00:36 UTC, peternewman approved these changes
LGTM thanks.

2022-10-19 00:36 UTC, peternewman commented
Force merging as Python 3.10 test is missing for some reason.

2022-10-19 00:37 UTC, merged