insuffient->insufficient
codespell-project/codespell pull request #2527
Opened 2022-10-14 07:59 UTC by tkoyama010

See https://github.com/pyvista/pyvista/pull/3464

2022-10-15 06:48 UTC, vikivivi requested changes

2022-10-15 06:48 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +insuffient->insufficient
```suggestion
insufficency->insufficiency
insufficent->insufficient
insufficently->insufficiently
insuffiency->insufficiency
insuffient->insufficient
insuffiently->insufficiently
```

2022-10-15 06:48 UTC, vikivivi commented on codespell_lib/data/dictionary.txt
> +insuffient->insufficient
* https://github.com/search?q=insufficency&type=code  393
* https://github.com/search?q=insufficently&type=code  620
* https://github.com/search?q=insuffient&type=code  66452
* https://github.com/search?q=insuffiently&type=code  208

You might also want to add the following as well.
```text
sufficency->sufficiency
suffiency->sufficiency
suffient->sufficient
suffiently->sufficiently
```
* https://github.com/search?q=sufficency&type=code  1206
* https://github.com/search?q=suffiency&type=code  666
* https://github.com/search?q=suffient&type=code  286066
* https://github.com/search?q=suffiently&type=code  35388

2022-10-17 11:46 UTC, peternewman approved these changes
LGTM thanks both.

2022-10-17 11:49 UTC, merged