Add a spelling correction
codespell-project/codespell pull request #2572
Opened 2022-10-31 06:00 UTC by fxlb

2022-11-02 10:21 UTC, DimitriPapadopoulos requested changes

2022-11-02 10:21 UTC, DimitriPapadopoulos commented on codespell_lib/data/dictionary.txt
> +initiailize->initialize
Please also add `initiailized`, `initiailizes`, `initiailizing`.

2022-11-02 12:19 UTC, fxlb commented
Done, thanks.

2022-11-02 12:39 UTC, luzpaz approved these changes

2022-11-02 12:44 UTC, DimitriPapadopoulos approved these changes

2022-11-04 15:00 UTC, merged

2022-11-04 15:00 UTC, luzpaz commented
Thanks @fxlb !