Add many corrections to dictionary.txt
codespell-project/codespell pull request #2608
Opened 2022-11-18 10:10 UTC by skangas

This adds several typos that I have in my own personal list of auto-corrections. I also added in several typos found in recent months in Emacs.

In other words, all these typos have been made in the wild at least once, often by yours truly.

2022-11-19 11:55 UTC, luzpaz commented
@skangas TY for the PR. Do you mind doing a 2nd run over your PR and add some plural forms that are missing?

2022-11-19 12:07 UTC, luzpaz requested changes

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +backwars->backwards
can also be `backward` since `d` key is right of `s`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +cantain->contain
add `cantains->contains`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +channge->change
Add `channges->changes`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +compilaiton->compilation
Add `compilaitons->compilations`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +conttributing->contributing
```
conttribute->contribute
conttributes->contributes
conttributed->contributed
conttribution->contribution
conttributions->contributions
```

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +copyirght->copyright
`copyirghts->copyrights`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +dialouge->dialogue
`dialouges->dialogues`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +packkage->package
`packkages->packages`

2022-11-19 12:07 UTC, luzpaz commented on codespell_lib/data/dictionary.txt
> +workaronud->workaround
`workaronuds->workarounds`

2022-11-19 13:54 UTC, skangas commented
> @skangas TY for the PR. Do you mind doing a 2nd run over your PR and add some plural forms that are missing?

Sure! Please see the latest commit with my fixes for the issues you mentioned. Thanks for reviewing.

BTW, since you mentioned key placement: note that I use dvorak instead of qwerty. So my typos will be a bit different.

2022-12-26 11:26 UTC, DimitriPapadopoulos approved these changes

2022-12-26 11:27 UTC, merged