Move `dateset` to rare
codespell-project/codespell pull request #2917
Opened 2023-07-04 05:52 UTC by DimitriPapadopoulos

Although it's hardly a word, it appears to have been added to the _aspell_ dictionary.

Fixes #2897.

2023-07-04 09:57 UTC, peternewman requested changes
Shouldn't we put it in code, given it's only a word in code contexts?

I've no idea if that sorts our Aspell check, and might mean it gets less used, but arguably could be more accurate too?

2023-07-04 10:01 UTC, peternewman commented
Also I like your suggestion here too @DimitriPapadopoulos : https://github.com/codespell-project/codespell/issues/2897#issuecomment-1606027622

2023-07-04 14:25 UTC, peternewman commented
> @korverdev Time permitting, could you test the following on Debian12? I don't think GitHub has a Debian runner, see [GitHub Actions Runner Images](https://github.com/actions/runner-images#available-images).

Although 22.04 is Jammy which has:
https://packages.ubuntu.com/jammy/aspell
AKA 0.60.8-4build1 which looks pretty similar to https://github.com/codespell-project/codespell/issues/2897#issue-1772887563

2023-07-04 14:41 UTC, DimitriPapadopoulos commented
The version of _aspell_ itself is probably irrelevant, we should focus on the version of dictionaries:
```
$ dpkg -l aspell-en
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-=================================
ii  aspell-en      2018.04.16-0-1 all          English dictionary for GNU Aspell
$ 
````
All (recent?) versions can be found here:
https://ftp.gnu.org/gnu/aspell/dict/en/

Indeed, Debian 12 Bookworm ships version `2020.12.07-0`, a more recent version than `2018.04.16-0`:
https://packages.debian.org/bookworm/aspell-en

2023-07-04 15:30 UTC, peternewman commented
> The version of _aspell_ itself is probably irrelevant, we should focus on the version of dictionaries. On my Ubuntu 22.04 workstation:

> Indeed, Debian 12 Bookworm ships version `2020.12.07-0`, a more recent version than `2018.04.16-0`: https://packages.debian.org/bookworm/aspell-en

You're of course right. It looks like we could probably manually download and install this https://packages.debian.org/bookworm/all/aspell-en/download

2023-07-04 17:42 UTC, DimitriPapadopoulos commented
Good idea. I have installed the latest Debian dictionary on my Ubuntu 22.04 workstation:
* My _master_ branch fails as expected.
* My _aspell_dateset_ branch, where the relevant fixes have been moved to `dictionary_rare.txt`, passes all tests.
* Moving these fixes to `dictionary_code.txt` works too.

2023-07-04 17:45 UTC, DimitriPapadopoulos commented
@peternewman Moved the fixes to `dictionary_code.txt`.

I am not sure about the `date set` suggestion. I haven't found a misspelling where `dateset` would actually stand for `date set` as in a `set of dates`. It's probably best to leave this as it is - or discuss it in a different pull request.

2023-07-04 17:55 UTC, DimitriPapadopoulos commented
This might be the actual `dateset` added to aspell:
[\<dateset\> Date Set](https://eadiva.com/dateset/)

2023-07-05 00:32 UTC, korverdev commented
> @korverdev Time permitting, could you test the following on Debian12? I don't think GitHub has a Debian runner, see [GitHub Actions Runner Images](https://github.com/actions/runner-images#available-images).
> 
>     1. Test this [_DimitriPapadopoulos:aspell_dateset_](https://github.com/DimitriPapadopoulos/codespell/tree/aspell_dateset) branch.
> 
>     2. Move the fix from [`codespell_lib/data/dictionary_rare.txt`](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_rare.txt) to [`codespell_lib/data/dictionary_code.txt`](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_code.txt) and test again:
>        ```
>        dateset->dataset
>        datesets->datasets
>        ```

@DimitriPapadopoulos Sure thing! I've tested both as requested. Both variants pass all tests.

2023-07-05 13:29 UTC, peternewman commented
> Good idea. I have installed the latest Debian dictionary on my Ubuntu 22.04 workstation:
> 
> * My _master_ branch fails as expected.
> * My _aspell_dateset_ branch, where the relevant fixes have been moved to `dictionary_rare.txt`, passes all tests.
> * Moving these fixes to `dictionary_code.txt` works too.

Excellent, I wonder if we should try and update that package more generally in our CI (probably in another PR)?

> I am not sure about the `date set` suggestion. I haven't found a misspelling where `dateset` would actually stand for `date set` as in a `set of dates`. It's probably best to leave this as it is - or discuss it in a different pull request.

Any of these with a missing space would be that typo:
"Opening date set for"
"Trial date set for"
"Date set for"

It also slightly neuters that correction in a good way, by forcing a choice rather than automagically fixing it.

2023-07-05 13:29 UTC, peternewman approved these changes
LGTM thanks, I think we should add dateset->date set too, but happy for you to decide or add it in a future PR or whatever...

2023-07-05 18:58 UTC, DimitriPapadopoulos commented
That's the thing: I haven't found such typos in GitHub:
"Opening dateset for"
"Trial dateset for"
"Dateset for"

It's always `dataset`. Perhaps I haven't searched enough.

2023-07-05 18:58 UTC, merged